default:
    path:
        directory: ./vendor/mvc5/mvc5/src
        extensions: php
        exclude:
    logging:
        report:
            xml:    ./build/logs/phpmetrics.xml
            html:   ./public/mvc5.html
            csv:    ./build/logs/phpmetrics.csv
        violations:
            xml:    ./build/logs/violations.xml
        chart:
            bubbles: ./public/bubbles.svg
