version: '3.5'

networks:
  public:
    external:
      name: traefik_webgateway

services:
  app:
    build:
      args:
        - XDEBUG=true
        - NODE_JS=true
        - RELEASE_VERSION=apache
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - LOCALE=${LOCALE}
        - TIME_ZONE=${TIME_ZONE}
      context: ~/docker
    container_name: mvc5playground
    #extra_hosts:
    #image: mvc5playground
    labels:
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:mvc5playground
      - traefik.port=80
    networks:
      - public
    volumes:
      - ~/.composer:/home/app/.composer
      - .:/var/www
